# Generated by Django 3.2.10 on 2022-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncodeDecodeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50)),
                ('is_encode', models.BooleanField()),
                ('result', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='HashResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.TextField(db_index=True, max_length=10000)),
                ('function_name', models.CharField(max_length=50)),
                ('bit_length', models.IntegerField()),
                ('result_base64', models.CharField(max_length=1024)),
                ('result_hex', models.CharField(max_length=1024)),
            ],
        ),
    ]
