# Generated by Django 3.2.10 on 2022-02-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashresult',
            name='plaintext',
            field=models.CharField(default='<UnknownPlainText>', max_length=10000),
        ),
    ]
